import { EditorState, basicSetup } from "@codemirror/basic-setup";
import { EditorView, keymap, KeyBinding } from "@codemirror/view";
import { defaultKeymap, indentMore, indentLess } from "@codemirror/commands";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";

import { getHashCode, updateHash, decodeHash, defaultHash } from "./urlHash";

const insertSoftTab = ({ state, dispatch }: EditorView) => {
  if (state.selection.ranges.some((r) => !r.empty)) {
    return indentMore({ state, dispatch });
  }

  dispatch(
    state.update(state.replaceSelection("  "), {
      scrollIntoView: true,
      userEvent: "input",
    })
  );
  return true;
};

const extendedKeymap: KeyBinding[] = [
  ...defaultKeymap,
  {
    key: "Tab",
    run: insertSoftTab,
    shift: indentLess,
  },
];

const view = new EditorView({
  state: EditorState.create({
    doc: getHashCode(),
    extensions: [
      basicSetup,
      oneDark,
      keymap.of(extendedKeymap),
      javascript({
        jsx: true,
        typescript: true,
      }),
    ],
  }),
  parent: document.getElementById("editor")!,
  dispatch: (tr) => {
    view.update([tr]);

    if (tr.docChanged) {
      const newCode = tr.newDoc.sliceString(0, tr.newDoc.length);
      updateHash(newCode);
      window.dispatchEvent(
        new CustomEvent("code", {
          detail: newCode,
        })
      );
    }
  },
});

const examples = [
  { name: "Select example...", hash: "" },
  {
    name: "Hacker News",
    hash: defaultHash,
  },
  // {
  //   name: "React Runner",
  //   hash: "JYWwDg9gTgLgBAbzgYQgEwKYFE3BtAGjgFcBnDAGWADcMAlYgO0YyiIGMoMBDGejAI7FgXOAF84AMygQQcAORdu7GAFoANjQyqoTFlHkAoUJFiI47dBgBC6iOwDW4qTLnzLIEBEaqY3AOakRoaWjKTwwIx4wNzqqJhwALwWVrb2DgAGhnBwJtDwSPHYuPhsJORUtAzMrBxKfHSCwqIS0rIKSioaWjp6rME5GAAepvCYktzE6vAAFACUSQB8iNk5KWEFcBjqGCAYjDBErDJllphE3sgAFtyM-hjOyWSUWtX6Mwira3CklmAYAC4Vt9vpForEigQviDMGAYFcgbD4XAANRwACMUJBay4QhEgIs9X4eK4H2h2MUPC6mlovRqBiBhSsODwhHKLyqfVORMaJIeYix2PEc0F3wF5NyURgMTiVlFwsM0OAkjgMyRVzgywATAAGBZcGDEKCMOCMKbqRXfA1Gk0zCUAHlw1B+MAAnjtEggkGBuGhcHcgfIABxgIZwHXhuAhobycRiRYSnL2oos0pwaixYgYT1nDASS43O7ZhAF273CQAegTQsQx2gcAAZA24PawFxFgg61AxPaK22MIsxImW06O9tdvsYD2K6OHTOaNW1nNVkOsoZhqM4ONJtNVQtEstPjlQuFzOO9gcjlAThw5XBS0XHuzKvQuWTvr8IP9GRKwdKIXKErqkCOryjkuLNASnA8A0TT4u+QqUsoag0touj0vIjIoMyJRss8L5vLUhIwcSkHiGBwryuKoJSjKkIrsuqzWsaqrQvai7fMmOGslA6aZsWub5ow1xlsWD7lnAVYSp2171k2Lb9mOsndr2ilDtijoLp2OwXlOvazpxUk5MuQ5AA",
  // },
  {
    name: "Tailwindcss",
    hash: 'PQKgBAKgFglgzmApgDwIYFsAOAbRYBOiAjgK4yEISozYDuMAdgCZgDCAyu2AG4BMAdAAYA1GBDAAUDCwB7fABcwAbzAAxfKgDm6RA0UBfMADN8M9GADkhVAGN5FqbIXKwABRmYZ3RPgA0kDQY4GHkYGQYwQxMzSwABKERUJlw4ODJgazsHaU9nFQBZXRIASRtw-wANUvDI41NzC3ifGRgyoIzEu2AZEnlsRkRsp0ULeWo6RiYbVNiBAQBGAE5gJnh5YDGaemZ+dEZ+abgHCTa4RQZUbhhNVFCagF4wAG0JMBcLnQAuS1dTJhIsv4oIQjN8LABiCyRXyvd4YRBg1SJeQkCgWIEgsGQ6GwlQfBGWfKofAAa0Q8hwtkGGMQoMs2P0MLeePhYNYZkwqAYAE90WBgbSsVDGRIALoSCQoXKKJi01AkbCKIwkBh2MIRACiaCwuAAFABKZSwwgo-ARXWwt4AHlW3DANmwqFSADl4fcAESER2hbxgABGmgAtLRYPI8F4fEZsDJaIHYExZQx3QA+S1vMA2mB2h1OuCunQe9CoZDBwMAdmQ2DA6BL8vkMhTafTGdt9sdLrdnsQ3qzeAAXoH5oIwJg-YGABz+oMhkJ4ODoT6jwcANmrTEXY94w+wmk+RZLsd4lbAO8+seV2Crp6XvEnlY3gYAzLxG823xm4NxNE3323c-nEA9eNExPXc-WjGwSTAVA-TgGRsF6PB8GuKB5EDYdGDgclA25dD+UDC8q1jAAWScw2QNCZzDMB5ECOAjDkcxaK5OBvUQQMS3mYAXx-d8jBobAPRsVFCD0dlo3wd1eLfK5EFoAAhGRkA9YdhyHNTBEEKTfzfTAKB8bwAEE4EwRA7AAJVuMIPQYcJEG0nT02JGBUDjGAE10D1aJIezpLeVNHPTK1PGwblNBqTxGHkOAPQAVkEXwNIS4d4t8dSwAS9T3TAYAAscq1gE-TRUz8jN3E8bx8DywLM2zds807L0rN9TA0NXTAS2IsB50XEtV2vEtx1fQKgouOr-0a7tmrwKMUDAWd0DgQMbF0MN8DAAArEgzhgIxcL9claEQXRuoXKBB23Xctp2vbAzOYl5Gy5zXMdA7BPdABxaM-VQbBhpGoLWxzDsC3dWbkHmsNFuW1afGMXAS00UxaHhlA7uBRgSTw09wcDJGY3Q-6AcBrM-xBwCwYRyHEGhla9Dh67Qlug75COk7zwVKt0HXWM6wbariebK1UH5EEPXBInBaFkyuTJhrQbgfBA3CUKUwAdTkEkoxjAqZYYAWpaC6Rv0NnTgflinzsnXnehkU7PnOocHNNt9FZsID5ApOBPmADZxm2f4YAOMxgGN4Bo3CuBgFoTXtdjItSUDSZrhkQNl00-giudl2coNqWCtQPPBdquWAI9QN0CV3hUYhhalrpta1wd9zE0l02rXKiN8H4eTenrCJzbL90A2DUMkJ6ZhECYCuWEwQNq8YfoGHY8Hqdp2H1sZ3bcIbuHyLQpHUFw4jNP5LvPn3vGNFw+Lhygc+R8P3D0oY4TvZ6PoBkDWzl+MGQ38+MhBgQZq6v22oAxgQZMLkj-gAoBUDmAp0DLfNuLsrR61Lp2RWysGCq2TAAeVMhEIsjBqxFF1pyfWpVi6FAYCUNomDQbnVXLGZcT1kKuWAp5d03l7K52oSNAqndKo9z7uEIuxMCq2gkTVFYWYZG-ikfIgRQsgb1SHlw4h65wL-ygtzPc2ALpNz0oGLq+iZYrQ4hOVBI0lBjWuFZcIuxUCYF1LqBahp7jJjABaHOGYRZkm5PcJQC1+D4kMAKIwwTQmRMMIPTsDE9AVynjAEgTEUAH2vsg0+99KoXwyVfI+gZFiaRsYLEJUMwnwn0CoxRwBC61ObPqfUNS0Ei0ieLbK8TQaJLQjoVYaSaIFOTuFNOOTz6XxGanFBCjAoABkZCaHmgwRpQV6mzLfEo7gGzrTADGhsrZJUAZWggHREI6palOmCeoLQOg9CtOJhvD0-wNB3AYIOeKSAnTsQ-tnQKG91BmA9B4WwIRcLDjgDYX67FFixT+Y5DeEAZDAs5DYMFF0IVQtwBi+FOlcCXApi8xx7z0qJCwknJMtT8XeEBegFFoL5DP1PpC6FOKqWJG8Ei+laLGV4RZdi2FuK3w7LKh4Lu-BXBcm7KssBcBVndIpjBOCCFqIDiHDRDweFoFoRLMOOe1dmJBHOTUQ19FGJgDkNcRggZ6xz2QpoVCTdNFCvfCK60aiJqg1MCqWU08dzdSgEkAm3Mpyj1nAQSBg4I3AMDOBWwUF4HK1Rei2KFrKpxzch5JMbqSbjXJh6DqyCRxoS6qvOuMN6ab22kzfah1jrZtWao5RfjrTG0bb+BVQEJxgBtvWF1Us3Yey9j7P2WxJhkGDugUO6BNDh0WTIKOMdSQZoTljKZYzBCZy-P2wWv15Aeh3SNXK7bdnSJPS2Umnb3QVyrmUyRwifCiM9jUK9I8qLjx9VPGeI557LKXivKm5bd5VpujvDeQyKKFOPuMvJl8n7ZLvg-IM8GX7-3AR-f9387KwPAYm0BaHvaJu1Thwjkb10zPPdLShjCKbYJVtyFMrBoxYWrNQYh5DCqUJzTpK0VQGFXuYT2tO7CXKZsTF5fAPlsrHpbRmYAD7u692fVQvxhz21qbQR6-N7pC3V1ar+pcj5uqovYs-O9gU7GXAcW85xrj3FQ08d43xLbhaUfTIE6JlTwlubeB0ipNN+CxJ8zRj0OjIIjhLEZzAuFq7esntPENl8fosd6ckgZ6TIPwbLDBnw+TMtZJKYhvJj8snxUPYFbjv5-PoCqToB5qn1nnuafV-OcjtnqdQOejp7oJbntfRBKCHNLwRaLdFp8EG0LAb-kk-pqSMtoXXenYcJWimfNybllbTKtLtsq28BZSzGDqca4bDTkj5NipEZK5e2ADnAFOSxY1Kn8rnYqj4I5+USED3UZ2dAaF1U1kDHzVjB5yzHkLV1Hqv3BzVx6oW1c+iofzH6ruKHW5QK9W7feVHQ0DlaYth6Hql8punkvrgIwj0RVWigPMELPCCnEWPMxSCkbQgOqVOENCGSNB+ngiwODBXmULkvrFY8+jL7LkrOZzZGD+u6LAPeReAwUwABFbgi3rEgBgyEbBQDANyHo+AKFcmTEoKEFgWvHJl990GYWoKTMQaMpb8vsCfEV8vFMKsBj+m2gMVIRunvHOANTynmBadQ6M0l75E2oMIftlD1NhOCn+sh8WUsx5Ie1ltk3ePTdL7HlPADrSObDIMGkNBRC80WBFk0BcaC-RSAiySNBFgP8wCyiwpJvQ3UVTyH4GAAAimQeaknCBgFIDAE8cgab2hIJgdyavFBlHQOgGQTAZB941P0RQaQu-wnkDKkgmgXKKG8KXjAFqbBQrMrcYwh-j915gA3-gtSCqYEp3joeOfIdoUnD1VePUt5bpicrpq1t47oxgFApcm0818dPQJ5fVv04BA019aAoDNlOs-Futes-Er0hsqwy0oZ65wNACwNK0RtJwxsjMed8BZR1pqDaCbU6JORRJFBI8UsOc0s5sCB4Cv1EsCl31Q1Fsct8BPgR511sthx9ExszF1xSclkpDOJtsXZdswAPoYF7oFAp4jsGkTs2sc0S4r1w8480IIUFx0BDFHw0ChYMCc4sDysO1rcKY8Ca414iCyCSCK1G5C0KDcIqC5BaD-R-CfBGCWJmDVpo9ksZoODZtBk4sEC+DINxDT4xCHdU50p1sRCUjVhRktxJD1xpDc8k95D8jFD7DmwVC5lew28aYZBtD9C9CX8GjA8z1ZFPsJFTshYmjNkP9OxTwlV4IK9TxtUcJsZdx7VUJRizxBxuIbErQ21AoBNkEWECJOYLU-QNozJJsu57Zzoyxq59FzpFhkcpjCJ0dzpCJ+1B13RUJh1fZpAtBEA4B+AVQTJ2woBJ1gBMB756wPlYp5hiJHxiJlwyxxxAxEBBAyxlwbBeBeBHxUBlxFheAAB+GASsGAP0e4fAMceYfgBYAAMlRPcnuEQG5AACkoAbAAAJeSIwVANWfvGAfBDaDUbkfIZXJgRYPEvme4BifAIseQPE-ifdGwUwTAPE2ge4W8eKPEoge4ccJQxyPdA9aSGTTZLo09ZtMAfUCQGpIAA'
  },
  {
    name: "React Select",
    hash: "JYWwDg9gTgLgBAZQKYBskGN4DMoRHAciiQENMBaAZ1QxgICh70IA7S+CMGYVyuAXjgBtenDgBvOADcSKAK5IAXIXQALCMxQkYSAgBo4WgEaplBAMLrN23XAC+e0ROmyFZ9lBIB3E1CgBPfUMSExQzBBhPHyQ-QPtHMUkZeSVCGRZgFC0g41NCADUSDKySAnt6AF1GJAAPSFg4ABMkLBI5FHgACgBKAQA+OE6nAB5kNEw4Tm5efnEpnjY7OAB6Pvpu+iA",
  },
  {
    name: "MUI",
    hash: "JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQokscAggG7IzJRxEnkABEAFdgAehCcsUYMgA2Y9p260G4aPABCwmDAgA7XsVJkhoiVJnyx23QdWMNcAMKpUmtFjnB9WI-1MRcUkYaVkFV3dPb18HdWYAFSwADxgAMWAvABN-EzNgy3CxJNSM7LimeDToEGcDGGI5ABlkACMvXMEgi1CrBWqoWvrGlva5CqdnAAssXABrVohkzsDzELDradmFpYnmJp85lfyejYUD-Tm9+ABxGRy+PO71vrE74CzruE0l4+fC6w-ZJfJoQeYAeR0MSwWQAkrgDH9zMAEfpUABaF5FUEQqE+GFfBIAT0gAHMoMgwFMiUiCr0isSyRSqUSvnV9Fx8TxHl01gCIvVkFyvgBvOC4ShSBIzEBYAA0cGlWFlAAViGwPtI4ABfWmnV6oGBEuRYVCqOgEYT6fDARF1MBEmSkqYwAAUYGIYFQAC4UPoiQBKOAiuhwOCUGDCKCGV2hsNwAA8jIg5Mp1LgHCsHIAvAAiRZZIkAJlz4ogcmgedCqQAdKhZgYstwiaX5MBSfo87gsBzpKWRTXBx6IF7tQA+OPx4Nke2O9suuAASvI2sn8YTFyOCIrUDzPhmMhgpamlAIeZdMC93rEElENYRIDEuYnU6nAE0IFG4AB1LCtVDAKEa5hgmYibmOIpkCuwHBr4ADucAACJSK6AY1qSWDpMIchyG+OBQKhq6vtONZkER67FCSKbMtSL5wAG9CrnQqKGnAMAyn42bipKoRKrKqH0HQKSVHAWRYAQyDYYQVo2oiADK7b6LC+iocGcYsfAUzIPoWQmnJwitCAgFwFxrpYGwPYwL62B4DANYDCAACiFkcgmAASCQALJNA5jkmrKHJjkG2ZjmpU7mZZNYehFHKIeJklyG6DFrhponKCZcDwXADnIVwZkuXZuBRpQHIJNwGEwMlU43nApoxDA6JZMAqBtCa6K+Kk6LQplEDoix5ZYClBioANNYVqSrohsRypCnIvpNlw6GYa6ZAzcA4wBnKMFgGgqBwdAWTzcoS1umQO1uPtUCfJta7alVOqCWGEZRjGa5JhxaoQBqYk8OxypYNmIp-bK44wQm7Kcr4PAPpAvg5rmkg+KWkjJN+HzsXmySoM+MEgZEHj1t1Yh0cRCZArj8aoMkgNTcRr6SFApI+AkI6+gAHFtdOvk1qBgHIyBEr6ZAECawKc1z8YiykiHAJQsn6EL27CCA+hkOLEsoN4HawqEIA+uQ3a9lAasU2G2rkcRJN0wmShcDwVM03AIC+gAjAqrSktu0BC-WqJNlARI1ojqs6qDGsgTicyQjA0JwqicDE6biaKBwdtW6TyapiyZbqHDMDni7paZrI8NTAArDj4dwApHZwD4SegZnNFEunr5k78MMGJZeYEDUpYGPphmAYDWk6XpBlGTAur6BAABqbYLX4DsimKIBWXALuh63GcpOkmRyFkSdTgzTOdrmM+DPIuZH-GlAAI6iJQh9V2Glo4WjWTsTfYYfHma1yNfF+cB+ZjDzI5RGchWBZCyJQNwgCX76GQLKP+ED4FV0knoOo4ATShBQbNNB4cMEQGqEVVAN9E5VyTLvMoB9v5O3Kj4PMF9JAALoffR+MI6FvzkB-L+QDEHINzOdPaB0CEaxAV4PMKpdqXSyGIiWRowAAyETI0RdDf4qIumooBRCsF80wsooqUASoNWEbI+RxEKHhwTA5CGIw2heDoaiBo5ZAbgxmPMRYywOByGEMoygsoQDtCgKWL2u4hEyAZi2BOY4LbhwkXIPM2BAnBKdlgCxr4rEazJjoPQ+g6GKOUagCegEMnEW4bwqYdDi7aXzrmZxQpfByLocvVe68ADMCogm+iLKHG+286Y10MMpG+oFbB5IGVOBM7wcgNK5JMtuMy666zgFjBZpNNxwBPOJPMABiIu3AS51ILMWSuQD4wDFJBAeAZiDoAH46EgTAocdZFEZmvJAkswCyoPnrk2dss8uZ9kZkObUvMJySy-KnCKXMiF7CaWQBZP0KBcAIitDAO51dFJwAAKpgFzHEyhzzLi-NAu80Zbx7gLLGUsAZNLkh0tnE6BcrSnbrw5k7VovoAAsocYlgzEBDRp0graNw+uqTUUA6LJW1EAA",
  },
  {
    name: "React Three Fiber",
    hash: "JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzksgGbZFIDKMKMScAvnKVBCHAORSoacBQoSLFxwAwigB2ANxSEKxAGJQUIBs1bsuAAR7oYAWhgALHkgD0pYACMkUAf1L5JGYBElwAQhAAeACjA2MEIASlx+ODhzczgAFWNgQjgeUjskFwYAd2AAGxy4AHNgaQYiOAATYB4MOHQ0JEIkmAg4EwY1QmMIuDR3QngO4zgAXgJiMj8Q7ui4KiR4fDA4froGUmhW4wZjCBKectrJA-1ihhX6bt7JfrgAbR29pHLsYhgACV27AF0Rsepaeh+UgoHLEKaRK43W4nEoveYAQVcJR+o0oNFWQJBYOmMSo+GshDQUBsDBMiR67EgknS8GamwYPCOdgMOQgEDA2DYANJWzggzgSD2AE8WCo1N1KMpVEg-H5zkhsOUkDlaGFhgA+OB+QYAOjQ+CgjJgOq5dDckh1PjgAGpRgAGHV2gCMIXBURiyBgBo80mASEy2DaxFqPGSSAK+ByKCgmzMOoAVkllUg1JIYEmfIEGsQDsAPAApKgADW6PC9UA8fm6kQAPINq5FcDrm4F2YRGA3IilhjhBh3G43CSCkD2YQwAPxwJ06gCscAAXFP+wO4O4xDlgGgANY9vyCmlqzWvREwU5+ACEY5Cy4H7gAChA8-QoAB5Pa7-dpw-LeYfPZ+GAoHwJBr07VdJAfJ87BffAYA-EovxGI9f0+KBMVBEDGHVMCa2sXwAHEkHYeYoBFaMCkIHtbidbAaKnL5mHMbCVzgOsGmMdEjmjcoAFlVmJEEKVZKAeweNIDknTgdhgMA8y3TgFy4aApAKJBOEY5jGxrcxBk0qYO34RklTQ7oawkGQ5E02tVGsP00wAGWAApjHgJiGxrSAn0c5z4EgQhgFPdwqKdO1aNCqc7QYqIrNY7wrT8gLzSogxpwAJmwcLIo09y4rgBLAskYKdXSuBMqitza3MczZEIbCQiAA",
  },
  {
    name: "canvas-confetti",
    hash: "JYWwDg9gTgLgBAYwgOwGYFMY2HVUIhwDkCAhsgG6kDOAtEmptkQFAsMZbAAUAlEA",
  },
  {
    name: "swr",
    hash: "JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWOAVwGckBlAdQTm1wPoHcozy5NBAB29LEhhoAFkihwAvHAAUtKABsAlIoB8HSTNUbNAOhiyRy5UXraFemyYBW9Ucs2aK5JAA9q8ABMkTBRadSxaEQxgUTgAQTAwdzgAb3I4OGExeBS4AJQYFAAaODkceQBfRTpGVgRldIyCaRgYMHoALgB6LpQwYBMAc2BzWgAjE2EQLqJIei6ANzk0JHUu3n4ixozMA1koRs9BDOBMFTLobSIYNRECOLuL+WkUejgINDQ1IgCTAROzsoAIT5QpXSS3AgAGQgKACwBEgxMyP+cGukIaTTgAB54QsdNsmtjpABGHQpUEoEwiFAgJAVbFdUkErEZbFgcmUkxBehoKDAMAwGIiBldDmEtniHCInSAXg3AII7qS59HGvP5Yzk9AA+sJIjBRVLRINyfgCBUJTjDTLABTkSoKVPEKCggxQAC9NTqIHqDTBpcaUqb8ObWZbfUadIAeDcALvt2womTDQADW2t1In1jKtxsJjLxLLgR3NQA",
  },
];

const select = document.getElementById("examples") as HTMLSelectElement;
select.onchange = () => {
  const hash = examples[select.selectedIndex].hash;
  view.dispatch({
    changes: {
      from: 0,
      to: view.state.doc.length,
      insert: decodeHash(hash),
    },
  });
};

examples.forEach((example) => {
  const option = document.createElement("option");
  option.innerText = example.name;
  select.appendChild(option);
});
